---

#requires following env variables
# HOST: host to connect to, can be defined in inventory file. e.g. user@host or host
# NEXTJS_REPO_ID: org/repo 
# NEXTJS_REPO_BRANCH: branch to checkout
# STRAPI_REPO_ID: org/repo
# STRAPI_REPO_BRANCH: branch to checkout
# GH_USER: github username
# GH_TOKEN: github token


- hosts: "{{ HOST }}"
  gather_facts: false

  tasks:
    - name: checkout nextjs repo
      git:
        repo: https://{{ GH_USER }}:{{ GH_TOKEN }}@github.com/{{ NEXTJS_REPO_ID }}
        dest: ~/nextjs
        version: "{{ NEXTJS_REPO_BRANCH }}"
        force: yes
        recursive: yes
        clone: yes
        depth: 1
      register: nextjs_repo

    - name: checkout strapi repo
      git:
        repo: https://{{ GH_USER }}:{{ GH_TOKEN }}github.com/{{ STRAPI_REPO_ID }}
        dest: ~/strapi
        version: "{{ STRAPI_REPO_BRANCH }}"
        force: yes
        recursive: yes
        clone: yes
        depth: 1
      register: strapi_repo


