---

#requires following env variables
# HOST: host to connect to, can be defined in inventory file. e.g. user@host or host
# NEXTJS_REPO_ID: org/repo 
# NEXTJS_REPO_BRANCH: branch to checkout
# STRAPI_REPO_ID: org/repo
# STRAPI_REPO_BRANCH: branch to checkout
# GH_USER: github username
# GH_TOKEN: github token


- hosts: "{{ HOST }}"
  gather_facts: false

  tasks:
    - name: checkout nextjs repo
      git:
        repo: https://{{ GH_USER }}:{{ GH_TOKEN }}@github.com/{{ NEXTJS_REPO_ID }}
        dest: ~/nextjs
        version: "{{ NEXTJS_REPO_BRANCH }}"
        force: yes
        recursive: yes
        clone: yes
        depth: 1
      register: nextjs_repo

    - name: checkout strapi repo
      git:
        repo: https://{{ GH_USER }}:{{ GH_TOKEN }}@github.com/{{ STRAPI_REPO_ID }}
        dest: ~/strapi
        version: "{{ STRAPI_REPO_BRANCH }}"
        force: yes
        recursive: yes
        clone: yes
        depth: 1
      register: strapi_repo

    - name: install pm2 using npm
      become: yes
      become_user: bitnami
      shell:
        cmd: sudo npm install pm2 -g
        executable: /bin/bash

    - name: install deps for nextjs
      npm:
        path: ~/nextjs
        production: yes
        registry: https://registry.npmjs.org/

    - name: install deps for strapi
      npm:
        path: ~/strapi
        production: yes
        registry: https://registry.npmjs.org/

    - name: build nextjs
      command: npm run build
      args:
        chdir: ~/nextjs

    - name: build strapi 
      command: npm run build
      args:
        chdir: ~/strapi

    - name: delete old pm2 processes
      become_user: bitnami
      command: pm2 delete all

    - name: start nextjs with pm2
      become_user: bitnami
      command: pm2 start npm --name "nextjs" -- start
      args:
        chdir: ~/nextjs

    - name: start strapi with pm2
      become_user: bitnami
      command: pm2 start npm --name "strapi" -- start
      args:
        chdir: ~/strapi



