---

- hosts: "{{ HOST }}"
  gather_facts: false

  tasks:
    - name: wait for connection
      wait_for_connection:
        delay: 5
        timeout: 600

    - name: configure AWS cli
      shell: |
        aws configure set aws_access_key_id {{ AWS_BACKUP_PUBLIC_KEY }}
        aws configure set aws_secret_access_key {{ AWS_BACKUP_PRIVATE_KEY }}
        aws configure set default.region {{ AWS_REGION }}

    - name: copy restore-strapi.sh script
      copy:
        src: restore-strapi.sh
        dest: ~/restore-strapi.sh
        mode: 0755

    - name: stop the strapi pm2 process
      shell: |
        pm2 stop strapi
        
    - name: run restore-strapi.sh script
      shell: |
        ~/restore-strapi.sh {{ S3_OBJECT_URL }} 

    - name: start the strapi pm2 process
      shell: |
        pm2 start strapi