---

- hosts: "{{ HOST }}"
  gather_facts: false

  tasks:
    - name: wait for connection
      wait_for_connection:
        delay: 5
        timeout: 600

    - name: configure AWS cli
      shell: |
        aws configure set aws_access_key_id {{ AWS_BACKUP_PUBLIC_KEY }}
        aws configure set aws_secret_access_key {{ AWS_BACKUP_PRIVATE_KEY }}
        aws configure set default.region {{ AWS_REGION }}

    - name: copy backup-strapi.sh
      template:
        src: backup-strapi.sh
        dest: ~/backup-strapi.sh
        mode: 0755

    - name: copy backup-strapi.sh
      template:
        src: backup-strapi-dev.sh
        dest: ~/backup-strapi-dev.sh
        mode: 0755
        
    - name: setup cron job to run script every day at midnight
      cron:
        name: backup-strapi
        minute: 0
        hour: 0
        job: /home/bitnami/backup-strapi.sh $(echo {{ NEXTJS_REPO_ID }} | tr / -)
        state: present

    - name: setup cron job to run script every day at midnight
      cron:
        name: backup-strapi-dev
        minute: 0
        hour: 0
        job: /home/bitnami/backup-strapi-dev.sh $(echo {{ NEXTJS_REPO_ID }} | tr / -)
        state: present

    - name: register the PATH variable
      shell: echo $PATH
      register: path

    - name: set the PATH variable for cron
      cron:
        name: PATH
        env: yes
        job: "{{ path.stdout }}"