---

#requires following env variables
# HOST: host to connect to, can be defined in inventory file. e.g. user@host or host
# DOMAIN: domain name, e.g. example.com
# STRAPI_DOMAIN_PREFIX: subdomain for strapi, e.g. strapi for strapi.example.com

- hosts: "{{ HOST }}"
  gather_facts: false

  tasks:
    - name: wait for connection
      wait_for_connection:
        delay: 5
        timeout: 600

    - name: install nginx
      become: yes
      apt:
        name: nginx
        state: latest

    - name: kill apache (VIOLENTLY)
      become: yes
      shell: sudo /opt/bitnami/ctlscript.sh stop apache

    - name: delete everything in sites-enabled
      become: yes
      shell: sudo rm -rf /etc/nginx/sites-enabled/*

    - name: delete everything in sites-available
      become: yes
      shell: sudo rm -rf /etc/nginx/sites-available/*

    - name: start nginx
      become: yes
      service:
        name: nginx
        enabled: yes
        state: started

    - name: copy nginx config template
      become: yes
      template:
        src: nginx.config
        dest: /etc/nginx/sites-available/{{ DOMAIN }}
        mode: 0644

    - name: enable nginx config
      vars: 
        domain: _
      become: yes
      file:
        src: /etc/nginx/sites-available/{{ DOMAIN }}
        dest: /etc/nginx/sites-enabled/{{ DOMAIN }}
        state: link

    - name: restart nginx
      become: yes
      service:
        name: nginx
        state: restarted
