---

- hosts: "{{ host }}"
  gather_facts: false

  tasks:
    - name: update packages
      become: true
      apt:
        update_cache: yes

    - name: install postgress
      become: true
      apt:
        name: 
          - postgresql
          - python3-psycopg2
        state: present
        force_apt_get: yes

    - name: run postgres
      become: yes
      service: name=postgresql state=started enabled=yes

    - name: create database
      become_user: postgres
      become: yes
      postgresql_db:
        name: "strapi"

    - name: create user
      become_user: postgres
      become: yes
      postgresql_user:
        name: "strapi"
        db: "strapi"
        password: "strapi"
        priv: "ALL"
        role_attr_flags: SUPERUSER
        state: present

     