---

- hosts: "{{ HOST }}"
  gather_facts: false

  tasks:
    - name: wait for connection
      wait_for_connection:
        delay: 5
        timeout: 600

    - name: download infisical
      become: true
      shell: "curl -1sLf 'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.deb.sh' | sudo -E bash"

    - name: install infisical
      become: true
      apt:
        name: infisical
        state: latest

    - name: create nextjs-dev template
      become: true
      become_user: bitnami
      template:
        src: run-nextjs-dev.sh
        dest: ~/nextjs
        mode: 0755

    - name: create nextjs template
      become: true
      become_user: bitnami
      template:
        src: run-nextjs.sh
        dest: ~/nextjs
        mode: 0755

    - name: create strapi-dev template
      become: true
      become_user: bitnami
      template:
        src: run-strapi-dev.sh
        dest: ~/strapi
        mode: 0755

    - name: create strapi template
      become: true
      become_user: bitnami
      template:
        src: run-strapi.sh
        dest: ~/strapi
        mode: 0755



