---

- hosts: "{{ HOST }}"
  gather_facts: false

  tasks:
    - name: wait for connection
      wait_for_connection:
        delay: 5
        timeout: 600

    - name: download infisical
      become: true
      shell: "curl -1sLf 'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.deb.sh' | sudo -E bash"

    - name: install infisical
      become: true
      apt:
        name: infisical
        state: latest



