---

- hosts: "{{ host }}"
  gather_facts: false

  tasks:
    - name: install nginx
      become: yes
      apt:
        name: nginx
        state: latest

    - name: copy nginx config template
      become: yes
      vars: 
        domain: test.com
        strapi_domain_prefix: strapi
      template:
        src: nginx.config
        dest: /etc/nginx/sites-available/{{ domain }}
        mode: 0644

    - name: kill apache
      become: yes
      shell: sudo /opt/bitnami/ctlscript.sh stop apache

    - name: start nginx
      become: yes
      service:
        name: nginx
        enabled: yes
        state: started

    - name: enable nginx config
      vars: 
        domain: test.com
      become: yes
      file:
        src: /etc/nginx/sites-available/{{ domain }}
        dest: /etc/nginx/sites-enabled/{{ domain }}
        state: link

    - name: unlink the default nginx config
      become: yes
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: restart nginx
      become: yes
      service:
        name: nginx
        state: restarted
