---

#requires following env variables
# HOST: host to connect to, can be defined in inventory file. e.g. user@host or host

- hosts: "{{ HOST }}"
  gather_facts: false

  tasks:
    - name: wait for connection
      wait_for_connection:
        delay: 5
        timeout: 600

    - name: install snapd
      become: true
      apt:
        name: snapd
        state: present

    - name: enable snapd
      become: true
      shell: systemctl enable --now snapd.socket

    - name: update snapd
      become: true
      shell: snap install core; snap refresh core

    - name: install certbot
      become: true
      shell: snap install --classic certbot

    - name: create certbot alias
      become: true
      file: 
        path: /usr/bin/certbot
        src: /snap/bin/certbot
        state: link

    - name: delete any existing certificates
      become: true
      shell: printf "\n" | sudo certbot delete --force-interactive

    - name: import setup-nginx playbook
      import_playbook: setup-nginx.ansible.yml
  
    - name: run certbot
      become: true
      shell: printf '{{ CERTBOT_EMAIL }}\nY\nN\n\n' | certbot --nginx 